// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonSearch.Context;

namespace PersonSearch.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20190316124307_AddedAttributesForRequiredFields")]
    partial class AddedAttributesForRequiredFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PersonSearch.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(120);

                    b.Property<string>("Country")
                        .HasMaxLength(120);

                    b.Property<int?>("PersonId");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("State")
                        .HasMaxLength(120);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Type");

                    b.HasKey("AddressId");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PersonSearch.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("Gender");

                    b.Property<string>("ImageName");

                    b.Property<string>("Interests");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Phone");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("PersonSearch.Models.Address", b =>
                {
                    b.HasOne("PersonSearch.Models.Person")
                        .WithMany("Address")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
